### ISSUE TITLE
Small typos in Documentation

### ISSUE THREAD

**Issue by seankdecker** [att-innovate/squanch#1]
Hi Ben!

There are just two small bugs that I found in your sample code that you may want to change:

both are in _Getting Started_ and both are just variable names being inconsistent, so not big.

First I believe
```
msg = "Hello, Bob!"
bits = string_to_bits(message)
```

Should become 

```
msg = "Hello, Bob!" 
bits = string_to_bits(msg)
```

Similarly later
```
mem = Agent.shared_hilbert_space(1, len(msgBits))  
out = Agent.shared_output()
```

should become

```
mem = Agent.shared_hilbert_space(1, len(bits))   
out = Agent.shared_output()
```

**Comment by bencbartlett** [comment]
Thanks for pointing this out -- that must have been left over from when I changed a lot of the syntax to be PEP compliant. Before I finish writing this whitepaper, I'm also going to change the way that agents get initialized to directly take a `QStream` instead of having to awkwardly use the `shared_hilbert_space` function every time.

**Comment by seankdecker** [comment]
Ah that's a good idea! Indeed it is a bit clunky to have to make the Hilbert space each time

**Comment by bencbartlett** [comment]
These have been fixed in the latest commit
